// This file is auto-generated by @hey-api/openapi-ts

import { client, type Options } from '@hey-api/client-fetch';
import type { ApiLoginCreateData, ApiLoginCreateError, ApiLoginCreateResponse, ApiLogoutCreateError, ApiLogoutCreateResponse, ApiSurveysListError, ApiSurveysListResponse, ApiSurveysCreateData, ApiSurveysCreateError, ApiSurveysCreateResponse, ApiSurveysRetrieveData, ApiSurveysRetrieveError, ApiSurveysRetrieveResponse, ApiSurveysDestroyData, ApiSurveysDestroyError, ApiSurveysDestroyResponse } from './types.gen';

export const apiLoginCreate = (options: Options<ApiLoginCreateData>) => { return (options?.client ?? client).post<ApiLoginCreateResponse, ApiLoginCreateError>({
    ...options,
    url: '/api/login/'
}); };

export const apiLogoutCreate = (options?: Options) => { return (options?.client ?? client).post<ApiLogoutCreateResponse, ApiLogoutCreateError>({
    ...options,
    url: '/api/logout/'
}); };

export const apiSurveysList = (options?: Options) => { return (options?.client ?? client).get<ApiSurveysListResponse, ApiSurveysListError>({
    ...options,
    url: '/api/surveys/'
}); };

export const apiSurveysCreate = (options: Options<ApiSurveysCreateData>) => { return (options?.client ?? client).post<ApiSurveysCreateResponse, ApiSurveysCreateError>({
    ...options,
    url: '/api/surveys/'
}); };

export const apiSurveysRetrieve = (options: Options<ApiSurveysRetrieveData>) => { return (options?.client ?? client).get<ApiSurveysRetrieveResponse, ApiSurveysRetrieveError>({
    ...options,
    url: '/api/surveys/{id}/'
}); };

export const apiSurveysDestroy = (options: Options<ApiSurveysDestroyData>) => { return (options?.client ?? client).delete<ApiSurveysDestroyResponse, ApiSurveysDestroyError>({
    ...options,
    url: '/api/surveys/{id}/'
}); };