// This file is auto-generated by @hey-api/openapi-ts

export type Session = {
    username: string;
};

export type Survey = {
    readonly id: number;
    readonly url: string;
    name: string;
    point_of_contact: string;
    phone_number: string;
    description: string;
    email: string;
    address?: string;
    systems: Array<(string)>;
    readonly created: string;
};

export type User = {
    username: string;
    password: string;
};

export type ApiLoginCreateData = {
    body: User;
};

export type ApiLoginCreateResponse = User;

export type ApiLoginCreateError = unknown;

export type ApiLogoutCreateResponse = unknown;

export type ApiLogoutCreateError = unknown;

export type ApiSessionRetrieveResponse = Session;

export type ApiSessionRetrieveError = unknown;

export type ApiSurveysListResponse = Array<Survey>;

export type ApiSurveysListError = unknown;

export type ApiSurveysCreateData = {
    body: Survey;
};

export type ApiSurveysCreateResponse = Survey;

export type ApiSurveysCreateError = unknown;

export type ApiSurveysRetrieveData = {
    path: {
        /**
         * A unique integer value identifying this survey.
         */
        id: number;
    };
};

export type ApiSurveysRetrieveResponse = Survey;

export type ApiSurveysRetrieveError = unknown;

export type ApiSurveysDestroyData = {
    path: {
        /**
         * A unique integer value identifying this survey.
         */
        id: number;
    };
};

export type ApiSurveysDestroyResponse = void;

export type ApiSurveysDestroyError = unknown;

export type $OpenApiTs = {
    '/api/login/': {
        post: {
            req: ApiLoginCreateData;
            res: {
                '200': User;
            };
        };
    };
    '/api/logout/': {
        post: {
            res: {
                /**
                 * No response body
                 */
                '200': unknown;
            };
        };
    };
    '/api/session/': {
        get: {
            res: {
                '200': Session;
            };
        };
    };
    '/api/surveys/': {
        get: {
            res: {
                '200': Array<Survey>;
            };
        };
        post: {
            req: ApiSurveysCreateData;
            res: {
                '201': Survey;
            };
        };
    };
    '/api/surveys/{id}/': {
        get: {
            req: ApiSurveysRetrieveData;
            res: {
                '200': Survey;
            };
        };
        delete: {
            req: ApiSurveysDestroyData;
            res: {
                /**
                 * No response body
                 */
                '204': void;
            };
        };
    };
};