openapi: 3.0.3
info:
  title: GetSurveys
  version: 1.0.0
  description: TODO
paths:
  /api/login/:
    post:
      operationId: api_login_create
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuthToken'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuthToken'
        required: true
      security:
        - knoxApiToken: [ ]
        - { }
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: ''
  /api/logout/:
    post:
      operationId: api_logout_create
      tags:
        - api
      security:
        - knoxApiToken: [ ]
      responses:
        '200':
          description: No response body
  /api/surveys/:
    get:
      operationId: api_surveys_list
      tags:
        - api
      security:
        - knoxApiToken: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Survey'
          description: ''
    post:
      operationId: api_surveys_create
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Survey'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Survey'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Survey'
        required: true
      security:
        - knoxApiToken: [ ]
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
          description: ''
  /api/surveys/{id}/:
    get:
      operationId: api_surveys_retrieve
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: A unique integer value identifying this survey.
          required: true
      tags:
        - api
      security:
        - knoxApiToken: [ ]
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
          description: ''
    delete:
      operationId: api_surveys_destroy
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          description: A unique integer value identifying this survey.
          required: true
      tags:
        - api
      security:
        - knoxApiToken: [ ]
      responses:
        '204':
          description: No response body
components:
  schemas:
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
        - password
        - username
    Survey:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        url:
          type: string
          format: uri
          readOnly: true
        name:
          type: string
          maxLength: 255
        point_of_contact:
          type: string
          maxLength: 255
        phone_number:
          type: string
          maxLength: 15
        description:
          type: string
          maxLength: 20000
        email:
          type: string
          format: email
          maxLength: 254
        address:
          type: string
          maxLength: 255
        systems:
          type: array
          items:
            type: string
          writeOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
      required:
        - created
        - description
        - email
        - id
        - name
        - phone_number
        - point_of_contact
        - systems
        - url
  securitySchemes:
    knoxApiToken:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
