openapi: 3.0.3
info:
  title: GetSurveys
  version: 1.0.0
  description: TODO
paths:
  /survey/surveys/:
    get:
      operationId: survey_surveys_list
      tags:
      - survey
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Survey'
          description: ''
    post:
      operationId: survey_surveys_create
      tags:
      - survey
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Survey'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Survey'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Survey'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
          description: ''
  /survey/surveys/{id}:
    get:
      operationId: survey_surveys_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - survey
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
          description: ''
    delete:
      operationId: survey_surveys_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - survey
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Survey:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
        point_of_contact:
          type: string
          maxLength: 255
        phone_number:
          type: string
          maxLength: 15
        description:
          type: string
        email:
          type: string
          format: email
          maxLength: 254
        address:
          type: string
          maxLength: 255
      required:
      - description
      - email
      - id
      - name
      - phone_number
      - point_of_contact
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
