// This file is auto-generated by @hey-api/openapi-ts

export const $Survey = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            readOnly: true
        },
        url: {
            type: 'string',
            format: 'uri',
            readOnly: true
        },
        name: {
            type: 'string',
            maxLength: 255
        },
        point_of_contact: {
            type: 'string',
            maxLength: 255
        },
        phone_number: {
            type: 'string',
            maxLength: 15
        },
        description: {
            type: 'string',
            maxLength: 20000
        },
        email: {
            type: 'string',
            format: 'email',
            maxLength: 254
        },
        address: {
            type: 'string',
            maxLength: 255
        },
        created: {
            type: 'string',
            format: 'date-time',
            readOnly: true
        }
    },
    required: ['created', 'description', 'email', 'id', 'name', 'phone_number', 'point_of_contact', 'url']
} as const;