// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ApiSurveysListResponse, ApiSurveysCreateData, ApiSurveysCreateResponse, ApiSurveysRetrieveData, ApiSurveysRetrieveResponse, ApiSurveysDestroyData, ApiSurveysDestroyResponse } from './types.gen';

/**
 * @returns Survey
 * @throws ApiError
 */
export const apiSurveysList = (): CancelablePromise<ApiSurveysListResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/surveys/'
}); };

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Survey
 * @throws ApiError
 */
export const apiSurveysCreate = (data: ApiSurveysCreateData): CancelablePromise<ApiSurveysCreateResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/surveys/',
    body: data.requestBody,
    mediaType: 'application/json'
}); };

/**
 * @param data The data for the request.
 * @param data.id A unique integer value identifying this survey.
 * @returns Survey
 * @throws ApiError
 */
export const apiSurveysRetrieve = (data: ApiSurveysRetrieveData): CancelablePromise<ApiSurveysRetrieveResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/surveys/{id}/',
    path: {
        id: data.id
    }
}); };

/**
 * @param data The data for the request.
 * @param data.id A unique integer value identifying this survey.
 * @returns void No response body
 * @throws ApiError
 */
export const apiSurveysDestroy = (data: ApiSurveysDestroyData): CancelablePromise<ApiSurveysDestroyResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/surveys/{id}/',
    path: {
        id: data.id
    }
}); };