// This file is auto-generated by @hey-api/openapi-ts

export type Survey = {
    readonly id: number;
    readonly url: string;
    name: string;
    point_of_contact: string;
    phone_number: string;
    description: string;
    email: string;
    address?: string;
    readonly created: string;
};

export type ApiSurveysListResponse = Array<Survey>;

export type ApiSurveysCreateData = {
    requestBody: Survey;
};

export type ApiSurveysCreateResponse = Survey;

export type ApiSurveysRetrieveData = {
    /**
     * A unique integer value identifying this survey.
     */
    id: number;
};

export type ApiSurveysRetrieveResponse = Survey;

export type ApiSurveysDestroyData = {
    /**
     * A unique integer value identifying this survey.
     */
    id: number;
};

export type ApiSurveysDestroyResponse = void;

export type $OpenApiTs = {
    '/api/surveys/': {
        get: {
            res: {
                200: Array<Survey>;
            };
        };
        post: {
            req: ApiSurveysCreateData;
            res: {
                201: Survey;
            };
        };
    };
    '/api/surveys/{id}/': {
        get: {
            req: ApiSurveysRetrieveData;
            res: {
                200: Survey;
            };
        };
        delete: {
            req: ApiSurveysDestroyData;
            res: {
                /**
                 * No response body
                 */
                204: void;
            };
        };
    };
};