# Generated by Django 5.0.6 on 2024-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("point_of_contact", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("description", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
    ]
