# Generated by Django 5.0.6 on 2024-07-09 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="survey",
            options={"ordering": ["created"]},
        ),
        migrations.AddField(
            model_name="survey",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
